### PR TITLE
Cleaning up

### PR DESCRIPTION
**Pull request by codedot**
Task statement:
* removes generated and unused files from the repository;
* adapts the historical `README` file to the new markdown syntax;
* delegates building to `make(1)`'s default rules as much as possible;
* simplifies the structure of the source tree;
* removes non-standard environment-specific rules;
* eliminates references of filenames from within source code;
* reveals all the warnings arising from headers.

Rationale:
* in order to remain within POSIX constraints, `heirloom-make` and `heirloom-yacc` have been used;
* the radical solution of merging all the header and export files into one single header was meant to reveal all possible re-declarations, and indeed revealed multiple issues, including implicit cross-dependencies between headers and dependency on `<stdio.h>` as well as definitions of variables (as opposed to declarations) which should not have occurred in any header files;
* flat source tree structure eliminates references to parent directory `..`, thus avoiding confusion about a subdirectory expected to contain an independent part but making use of external facilities.

Further work:
* passes building using `heirloom-lex` instead of Flex, in particular `yy_create_buffer`, `yypush_buffer_state`, and `yypop_buffer_state` to be avoided as non-standard;
* passes building using `make debug` with `CFLAGS="-Wall -Werror"`;
* provides a more comprehensive testing input;
* implements a non-interactive mode in which input is read from a file;
* disables the interactive mode if standard input is not a terminal device.

### CODE REVIEW

**Comment by codedot** [comment]
> I am not sure I like the idea to merge all `h` and `e` files into a single file. Don't you loose track of the dependencies in this way?

It is entirely up to you to choose the refactoring strategy as you see fit.

The suggested direction is just one possible way mainly based on the observation that dependencies were _originally_ implicit and remained invisible until the local headers have been merged and included prior to the system ones.

It is likely that independent components can be factored out into sublibraries, however such components are yet to identified and their identification is simplified by the merge done.

**Comment by asperti** [comment]
The suggested direction is just one possible way mainly based on the observation that dependencies were originally implicit and remained invisible until the local headers have been merged and included prior to the system ones.


Why you say that dependecies were implicit? Any .c files included the .h  .e files it

depended upon.

**Comment by codedot** [comment]
> Why you say that dependecies were implicit?

Analysis has shown that compilability breaks by changing the order of header inclusion.

**Comment by asperti** [comment]
> Analysis has shown that compilability broke by changing the order of header inclusion.


So... ?

Sorry, I am not following. I really do not see the benefit to merge everything together.

I am sure you are right, but I fear that to convince me you will need to explain what you are doing in more detail.




-

**Comment by codedot** [comment]
> I really do not see the benefit to merge everything together.

If the rationale included in the current pull request's description looks suspicious, it may be wise to close this pull request and choose a different refactoring strategy.

**Comment by asperti** [comment]
Dear Anton,


Simply, I do not understand. I have not programmed in C for twenty years.

Since, to me, it does seem to be a good idea to have a single bohm.h file

I would like to better understand your reasons for proposing it.

-- andrea


________________________________

**Comment by codedot** [comment]
Of course, having one single header file that is too large can not be considered a good state in the long term. However, the proposed merge is temporary and technical, aimed at disclosing warnings and possible errors. Once all the revealed warnings have gone, splitting the merged header into independent parts immediately becomes one of the next steps to do.

**Pull request merged**
